### PR TITLE
update

### PR DESCRIPTION
**Pull request by skeetzo**
Hallo. (Thanks for the plugin and apparently alllllot of nodebb work.) Few minor updates. You mention not to outright trust your implementation in prod but I'm not sure there's even much room for error to begin with. The login prompt on home page was annoying, so I added a check for the actual web3 login page-- couldn't figure out how to add a prettier page for the POST login though. Added a redirect back to the home page as well after login, which naturally, worked until it didn't for no reason at all until I had to add a workaround for plausibly no reason. Very helpful that you already adding the "associate to account", I was worried I might have to add that. Thanks again for all the work.

Didn't need to change any of the admin settings. Or haven't, yet.

But yeah, should be good for live. I'll be using it as such soon, so, one way to find out.

### CODE REVIEW

**Comment by psychobunny** [comment]
Well done! Thank you. You should add yourself to the readme and I’m happy to give you access rights if you’d like to continue on this project. I’m happy to see someone work on this, thank you again.

**Comment by skeetzo** [comment]
Oh. Right. I can delete this fork now. *cough* I too have no idea what I'm doing. I made a change to the url in the plugin.json file not understanding what happens after actually doing a mythical pull request... (you might want to change that, or I can again *sigh*). I don't expect to need to make any changes again myself soon but if it helps, sure.

My project is 18+ hahaa but I wouldn't mind adding it ;)

**Comment by psychobunny** [comment]
Maybe not just for the sake of this project being used by hopefully as many as possible haha. I have no qualms either way but best of luck with your site! Yeah I noticed the plugin.json change but I’m not at a computer atm so I was thinking I’ll fix that next time. But if you don’t mind, I’d appreciate it. Thanks either way

**Comment by psychobunny** [comment]
It’s not a big deal because it’s not published on npm. So no worries btw

**Comment by skeetzo** [comment]
Hahaaa... yeah. I will figure out how to do the thing again. First pull request.

**Pull request merged**
